# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - YouTubeRAG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: youtuberagdocker.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8417AC8BB86F4D9C8D39D9E6866F7974 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_C0E4DE95E9AB4D4590C98537906B95B7 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: youtuberagdocker.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8417AC8BB86F4D9C8D39D9E6866F7974 }}/youtuberagdockerimage:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EBA13EEE8F4E423CB0FA6A366D7AF6EB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_95F582EEB3C9486D93ED3580F8A4DA82 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EAF7F086A43446CF86394059FDB8E3AF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YouTubeRAG'
          slot-name: 'Production'
          images: 'youtuberagdocker.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8417AC8BB86F4D9C8D39D9E6866F7974 }}/youtuberagdockerimage:${{ github.sha }}'
          