# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - YouTubeRAG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: youtuberagdocker.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_56F9D6AB1EBC43C2AC453541AC42ED17 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_9969C078F2384F34980C57CE586CDFCC }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: youtuberagdocker.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_56F9D6AB1EBC43C2AC453541AC42ED17 }}/youtube-rag-docker:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_42CF76465C844357BCA7AD42D15B7E72 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_987DC39BF37D419B8CCD4607A2618A16 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21ED5EE30E744C0F95044BAF5B75D014 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YouTubeRAG'
          slot-name: 'Production'
          images: 'youtuberagdocker.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_56F9D6AB1EBC43C2AC453541AC42ED17 }}/youtube-rag-docker:${{ github.sha }}'
          